ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name='cart'
urlpatterns = [

    path('addcart/<n>',views.addcart,name="addcart"),
    path('cartview',views.cartview,name="cartview"),
    path('cart_remove/<n>',views.cart_remove,name="cart_remove"),
    path('full_remove/<n>',views.full_remove,name="full_remove"),
    path('orderform',views.orderform,name="orderform"),
    path('orderview',views.orderview,name="orderview"),
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('',include('search.urls')),
    path('',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
from search import views
app_name='search'
urlpatterns = [

    path('search',views.search,name="search"),

]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name='shop'
urlpatterns = [
    path('',views.allcategories,name="allcat"),
    path('allprod/<p>',views.allproducts,name="allproducts"),
    path('detail/<str:p>',views.detail,name="detail"),
    path('register',views.register,name="register"),
    path('userlogin',views.userlogin,name="userlogin"),
    path('userlogout',views.userlogout,name="userlogout"),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Products
from django.contrib.auth.models import User
from django.http import HttpResponse
class Cart(models.Model):
    products=models.ForeignKey(Products,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.products.name

    def subtotal(self):
        return self.quantity*self.products.price


class Order(models.Model):
    products = models.ForeignKey(Products, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    no_of_items = models.IntegerField()
    address = models.TextField()
    phone = models.IntegerField()
    order_status = models.CharField(max_length=20,default="pending")
    delivery_status = models.CharField(max_length=20,default="pending")
    ordered_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Account(models.Model):
    acctnum = models.CharField(max_length=20)
    accttype = models.CharField(max_length=20)
    amount = models.IntegerField()

    def __str__(self):
        return self.acctnum

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/shop/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
class Category(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField(default=0)
    image=models.ImageField(upload_to="category",null=True,blank=True)

    def __str__(self):
       return self.name

class Products(models.Model):
    name=models.CharField(max_length=20)
    desc=models.TextField(default=0)
    image=models.ImageField(upload_to="products",null=True,blank=True)
    price=models.DecimalField(max_digits=10, decimal_places=2)
    stock=models.IntegerField(default=0)
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
       return self.name

ecommerce/cart/views.py
from django.shortcuts import render
from cart.models import Cart,Account,Order
from shop.models import Products
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

@login_required
def cartview(request):
    total=0
    u=request.user
    try:
        cart=Cart.objects.filter(user=u)
        for i in cart:
            total+=i.quantity*i.products.price
    except:
        pass

    return render(request,'cartview.html',{'c':cart,'total':total})


@login_required
def addcart(request,n):
    p=Products.objects.get(name=n)
    u=request.user
    try:
        cart=Cart.objects.get(user=u,products=p)
        if(p.stock > 0):

            cart.quantity+=1
            cart.save()
            p.stock -= 1
            p.save()
    except:
        if(p.stock > 0):
            cart=Cart.objects.create( products=p,user=u,quantity=1)
            cart.save()
            p.stock-=1
            p.save()

    return cartview(request)

@login_required
def cart_remove(request,n):
    p = Products.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, products=p)
        if (cart.quantity > 1):
            cart.quantity -= 1
            cart.save()
            p.stock+=1
            p.save()
        else:
            cart.delete()
            p.stock += 1
            p.save()
    except:
          pass
    return cartview(request)

@login_required
def full_remove(request,n):
    p = Products.objects.get(name=n)
    u = request.user
    try:
        cart = Cart.objects.get(user=u, products=p)
        cart.delete()
    except:
        pass
    return cartview(request)


@login_required
def orderform(request):
    if request.method=="POST":
        a=request.POST['a']
        p=request.POST['p']
        n=request.POST['n']

        u=request.user
        cart=Cart.objects.filter(user=u)
        total=0
        for i in cart:
            total+=i.quantity*i.products.price
        try:
            num=int(n)
            ac=Account.objects.get(acctnum=n)

            if(ac.amount>=total):
                ac.amount=ac.amount-total
                ac.save()
                for i in cart:
                    o=Order.objects.create(user=u,products=i.products,address=a,phone=p,no_of_items=i.quantity,order_status="paid")
                    o.save()
                cart.delete()
                msg="order placed successfully"
                return render(request,'orderdetail.html',{'msg': msg})
            else:
               msg="cannot place order"
               return render(request, 'orderdetail.html', {'msg': msg})
        except:
            pass
    return render(request, 'orderform.html')

@login_required
def orderview(request):
    u = request.user
    o=Order.objects.filter(user=u)
    return render(request,'orderview.html',{'o':o,'u':u.username})

ecommerce/search/views.py
from shop.models import Products
from django.shortcuts import render
from django.db.models import Q
def search(request):
    query = ""
    product= None

    if(request.method == "POST"):

        query = request.POST['q']

        product = Products.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
    return render(request,'search.html',{'query':query,'p':product})

ecommerce/shop/views.py
from django.shortcuts import render
from shop.models import Category,Products
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponse

def allcategories(request):
    c=Category.objects.all()
    return render(request,'category.html',{'c':c})

def allproducts(request,p):
    c =Category.objects.get(name=p)
    p= Products.objects.filter(category=c)
    return render(request,'products.html', {'c':c,'p':p})


def detail(request,p):
    p =Products.objects.get(name=p)
    return render(request,'detail.html', {'p':p})

def register(request):

        if (request.method== "POST"):
            u = request.POST['u']
            p = request.POST['p']
            cp = request.POST['cp']
            e = request.POST['e']
            f = request.POST['f']
            l = request.POST['l']

            if (p == cp):
                user = User.objects.create_user(username=u, password=p, email=e, first_name=f, last_name=l)
                user.save()
                return redirect('shop:allcat')
            else:
                return HttpResponse("passwords are not same")
        return render(request, 'register.html')

def userlogin(request):
    if (request.method=="POST"):
        u=request.POST['u']
        p=request.POST['p']
        user=authenticate(username=u,password=p)
        if user:
            login(request,user)
            return redirect('shop:allcat')
        else:
            return  HttpResponse("invalid credential")
    return render(request,'userlogin.html')


def userlogout(request):
    logout(request)
    return redirect('shop:userlogin')

ecommerce/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />


<link href="https://fonts.googleapis.com/css2?family=Noto+Sans:ital@1&display=swap" rel="stylesheet">
</head>
<body>
<header>
    <center>
    <img src="{% static 'images/log.png' %}" height="150px" width="150px"></center>
</header>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Eshop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'shop:allcat' %}">Home</a>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            All categories
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for i in links %}
            <li><a class="dropdown-item" href="{% url 'shop:allproducts' i.name %}">{{i.name}}</a></li>
              {% endfor %}
             </ul>
           </li>
          {% if user.is_authenticated %}

          <li class="nav-item">
                 <a class="nav-link" href="userlogout">Logout</a>
             </li>
          {% if user.is_superuser == False %}
            <li class="nav-item">
                 <a class="nav-link fs" href="{% url 'cart:cartview' %}"> <i class="fa-solid fa-cart-shopping"></i><sub class="ms-2">{{count}}</sub></a>
             </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'cart:orderview' %}">Your Order </a>
             </li>
          {% endif %}
          {% else %}
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'shop:register' %}">Register</a>
             </li>
             <li class="nav-item">
                 <a class="nav-link" href="{% url 'shop:userlogin' %}">Login</a>
             </li>

          {% endif %}



      </ul>
      <form class="d-flex" method="POST" action="{% url 'search:search' %}">
         {% csrf_token %}
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
{% block content %}

{% endblock %}


{% block category %}

{% endblock %}
<footer class="fixed-bottom">
<div class="footer">
    <div>

    <p style=><i class="fa-solid fa-copyright"></i><b> Eshop@pvt ltd.All rights reserved | </b></p>
</div>
</div>
</footer>
</body>
</html>

ecommerce/templates/cartview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>
<div class="container mt-5" style="margin-bottom:100px;">
    <div class="row">

        <h3 class="text-center">Shopping Cart</h3>
        <div class="col-7"><table class="table table-bordered">
            <tr><th colspan="5">Cart Items</th></tr>

            {% for i in c %}
        <tr><td>
         <img src="{{i.products.image.url}}" height="150px" width="150px">
        </td>
            <td><h6>{{i.products.name}}</h6> </td>
            <td><h6>Product Id:{{i.products.id}}</h6>
                <h6>Unit Price :{{i.products.price}}</h6>
                <h6>Quantity :{{i.quantity}}*{{i.products.price}}</h6>
            </td>
            <td>Subtotal :{{i.subtotal}}</td>
            <td>
                {% if i.products.stock > 0 %}
                <a href="{% url 'cart:addcart' i.products.name %}"><i class="fa-solid fa-circle-plus"></i></a>
                <a href="{% url 'cart:cart_remove' i.products.name %}"><i class="fa-solid fa-circle-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.products.name %}"><i class="fa-solid fa-trash"></i></a>
                {% else %}

                <a href="{% url 'cart:cart_remove' i.products.name %}"><i class="fa-solid fa-circle-minus"></i></a>
                <a href="{% url 'cart:full_remove' i.products.name %}"><i class="fa-solid fa-trash"></i></a>

            </td>

        </tr>
             {% endif %}
            {% endfor %}
    </table>

</div>
    <div class="col-4"> <table class="table table-bordered">

            <tr><th colspan="5">Check Out</th></tr>
        <tr><td>TOTAL :{{total}}</td></tr> </table>
        <a href="{% url 'cart:orderform' %}" class="btn btn-danger" style="position:absolute;right:480px;" >Place Order</a>
            <a href="" class="btn btn-danger" style="position:absolute;right:300px;">Continue shopping</a>
    </div >




    </div>
</div>
</center>
    {% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div>
    <img src="{% static 'images/ban.jpg' %}" height="500px" width="100%">
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px">
<h3 class="text-center fw-bold">Our Collections</h3>
<p style="text-align:justify;line-height:2;">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
</div>
{% endblock %}


{% block category %}
<h1>Collection</h1>
<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
    {% for i in c %}
    <div class="col-sm-4">
        <div class="card" style="width:30rem;" >
            <img src="{{i.image.url}}" width="80%" height="200px"  class="card-img-top" >
            <div class="card-body">
            <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
            <p class="card-text"> </p>
            <a href="{% url 'shop:allproducts' i.name %}" class="btn btn-primary">Products</a>

  </div>
</div>
    </div>
    {% endfor %}

</div>
</div>
{% endblock %}

ecommerce/templates/detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5" style="margin-bottom:100px;">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ p.image.url }}" style="height: 400px; width: 400px;" alt="{{ p.name }}">
        </div>
        <div class="col-md-6">
            <div class="choco">
                <h3>{{ p.name }}</h3>
                <p>{{ p.desc }}</p>
                <h5>{{ p.stock }} pieces left </h5>
                <h3>{{p.price}}</h3>
            </div>
            <div style="position: relative; z-index: 1;">

                {% if user.is_superuser == True %}
                    {% if p.stock == 0 %}
                        <h2>Out of stock</h2>
                        <a href="{% url 'admin:index'  %}" class="btn btn-danger d-block mx-auto">Add Stock</a>
                    {% else %}
                        <h2>Product in stock</h2>
                        <a href="{% url 'admin:index'  %}" class="btn btn-danger d-block mx-auto">Add Stock</a>
                    {% endif %}

                {% else %}
                    {% if p.stock == 0 %}
                    <h2>Out of stock</h2>

                    {% else %}
                    <h2>Product in stock</h2>
                    <a href="{% url 'cart:addcart' p.name %}" class="btn btn-danger d-block mx-auto">Add to cart</a>
                    {% endif %}
            {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock %}
</body>
</html>

ecommerce/templates/orderdetail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}


{% block content %}

{{msg}}
{% endblock %}

ecommerce/templates/orderform.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<center>
<div class="container mt-5" style="margin-bottom:100px;">
    <h3>OrderForm</h3>

    <form method="POST">
    {% csrf_token %}
<div class="mb-2">
  <label  class="form-label">Address</label>
  <input type="text" class="form-control"  name="a" placeholder="Enter Address ">
</div>

        <div class="mb-3">
  <label  class="form-label">Phn NO</label>
  <input type="number" class="form-control" name="p" placeholder="Enter the phn No.">
</div>

<div class="mb-3">
  <label  class="form-label">Acc NO</label>
  <input type="number" class="form-control" name="n" placeholder="Enter account No.">
</div>

  <input type="submit" class="form-control">


    </form></div>



    </center>


{% endblock %}

ecommerce/templates/orderview.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-bottom:100px;">
    <table class="table">
        <thead>
            <tr>
                <th>Name of the Customer</th>
                <th>Product Name</th>
                <th>Product Price</th>
                <th>Delivery Address</th>
                <th>No. of Items</th>
                <th>Ordered On</th>
                <th>Delivery Status</th>
                <th>Product Image</th>
            </tr>
        </thead>
        <tbody>
            {% for i in o %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ i.products.name }}</td>
                    <td>{{ i.products.price }}</td>
                    <td>{{ i.address }}</td>
                    <td>{{ i.no_of_items }}</td>
                    <td>{{ i.ordered_date }}</td>
                    <td style="color: #B7CAB4;">{{ i.delivery_status }}</td>
                    <td><img src="{{ i.products.image.url }}" height="100px" width="100px"></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div>
    <img src="{{c.image.url}}" height="500px" width="100%">
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px">
<h3 class="text-center fw-bold">{{c.name}}</h3>
<p style="text-align:justify;line-height:2;">{{c.desc}}</p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
    {% for i in p %}
    <div class="col-sm-4">
        <div class="card" style="width:30rem;" >
            <img src="{{i.image.url}}" width="80%" height="200px"  class="card-img-top" >
            <div class="card-body">
            <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
                <h5 class="card-title text-center fw-bold">{{i.price}}</h5>
            <p class="card-text"> </p>
            <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary">Details</a>

  </div>
</div>
    </div>
    {% endfor %}
        </div>
    </div>
{% endblock %}

ecommerce/templates/register.html
<!DOCTYPE html>
{% extends 'base.html'%}
{% load static %}
{% block content %}
<div class="container-fluid" style="margin-bottom:100px;">
<center>
<h3 class="mt-4">Register</h3>

<form method="POST">
    {% csrf_token %}
<div class="mb-2">
  <label  class="form-label">username</label>
  <input type="text" class="form-control"  name="u" placeholder="Enter username ">
</div>
<div class="mb-2">
  <label  class="form-label">password</label>
  <input type="password" class="form-control" name="p" placeholder="password">
</div>
    <div class="mb-3">
  <label  class="form-label">confirm password</label>
  <input type="password" class="form-control" name="cp" placeholder=" confirm password">
</div>
<div class="mb-3">
  <label  class="form-label">email</label>
  <input type="text" class="form-control" name="e" placeholder="Enter the email">
</div>
<div class="mb-3">
  <label  class="form-label">first name</label>
  <input type="text" class="form-control" name="f" placeholder="Enter the firstname">
</div>
    <div class="mb-3">
  <label  class="form-label">last name</label>
  <input type="text" class="form-control" name="l" placeholder="Enter the lastname">
</div>

  <input type="submit" class="form-control">

    </div>
    </form></div>

</center>
{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div>
    <h3>You have searched for {{query}}</h3>
</div>

<div class="container-fluid mt-3" style="margin-bottom:100px">
<h3 class="text-center fw-bold">{{c.name}}</h3>
<p style="text-align:justify;line-height:2;">{{c.desc}}</p>
</div>

<div class="container-fluid" style="margin-bottom:100px;">
    <div class="row">
        {% if p %}
        {% for i in p %}
    <div class="col-sm-4 mb-5">
        <div class="card" style="width:30rem;" >
            <img src="{{i.image.url}}" width="80%" height="200px"  class="card-img-top" >
            <div class="card-body">
            <h5 class="card-title text-center fw-bold">{{i.name}}</h5>
                <h5 class="card-title text-center fw-bold">{{i.price}}</h5>
            <p class="card-text"> </p>
            <a href="{% url 'shop:detail' i.name %}" class="btn btn-primary">Details</a>

  </div>
</div>
    </div>
    {% endfor %}
     {% else %}
        <h5 class="text-center">Result not found</h5>
     {% endif %}
        </div>
    </div>
{% endblock %}

ecommerce/templates/userlogin.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<center>

  <form method="POST">
    {% csrf_token %}
  <h3 class="mt-4">Login</h3>
<div class="mb-3">
  <label  class="form-label">username</label>
  <input type="text" class="form-control"  name="u" placeholder="Enter username ">
</div>
<div class="mb-3">
  <label  class="form-label">password</label>
  <input type="password" class="form-control" name="p" placeholder="password">
</div>

</div>
  <input type="submit" class="form-control" >
</div>
</center>
    </form>
{% endblock %}